# 미니배치 버전 파이썬 구현

In [1]:
import numpy as np

X = np.random.rand(10,2)
X

array([[0.28302656, 0.58173863],
       [0.09364822, 0.59912827],
       [0.91301446, 0.36201336],
       [0.80011085, 0.49343053],
       [0.01159919, 0.71319045],
       [0.82287515, 0.72588161],
       [0.55014275, 0.33026651],
       [0.2751846 , 0.77324223],
       [0.98542902, 0.90609763],
       [0.7327772 , 0.77577582]])

In [3]:
W1 = np.random.rand(2,4)
W1

array([[0.59598215, 0.89082106, 0.35319665, 0.4465849 ],
       [0.05508001, 0.27488408, 0.28024292, 0.37566034]])

In [4]:
b1 = np.random.rand(4)
b1

array([0.33055091, 0.84781233, 0.66556899, 0.27488686])

In [5]:
H = np.matmul(X,W1) + b1
H

array([[0.53127186, 1.25984903, 0.92856116, 0.61981837],
       [0.41936357, 1.09592695, 0.86654668, 0.54177746],
       [0.89463093, 1.76065655, 1.08949432, 0.81861939],
       [0.83458085, 1.69620412, 1.08644587, 0.81756656],
       [0.37674636, 1.05418983, 0.86953236, 0.54798425],
       [0.86095138, 1.78038014, 1.15962892, 0.9150554 ],
       [0.67661725, 1.42867608, 0.95243242, 0.64464033],
       [0.53714621, 1.30550454, 0.97945893, 0.68825658],
       [0.96775688, 1.97472506, 1.26754666, 1.05534952],
       [0.81000278, 1.71383411, 1.14178912, 0.8935623 ]])

# Sigmoid 함수

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [7]:
import matplotlib.pyplot as plt
zs = np.arange(-10,10,0.1)
gs = [sigmoid(z) for z in zs]
plt.plot(zs,gs)
plt.xlabel('z')   # z = - (X*W + b)
plt.ylabel('1/(1+e^z)')
plt.show()

<Figure size 640x480 with 1 Axes>

In [8]:
# 1 Layer Logistic Regression(Binary classification)
X = np.random.rand(10,2)
W1 = np.random.rand(2,4)
b1 = np.random.rand(4)
a = np.matmul(X,W1) + b1
h = sigmoid(a)
h

array([[0.71876094, 0.6577896 , 0.74596668, 0.79015043],
       [0.70202376, 0.63702138, 0.67547144, 0.71414539],
       [0.71315894, 0.64747981, 0.75865647, 0.80100575],
       [0.70153165, 0.63556225, 0.68337875, 0.72217239],
       [0.7427711 , 0.69348366, 0.77916591, 0.82787851],
       [0.73727675, 0.68916468, 0.72963667, 0.77949014],
       [0.64683697, 0.55952349, 0.54787327, 0.55722145],
       [0.71813757, 0.65967899, 0.71403092, 0.7584477 ],
       [0.71932268, 0.65923361, 0.74025618, 0.78472756],
       [0.71517095, 0.66092099, 0.64059752, 0.68220424]])

In [9]:
# 2 Layer Logistic Regression(Binary classification)
X = np.random.rand(10,2)
W1 = np.random.rand(2,4)
b1 = np.random.rand(4)

W2 = np.random.rand(4,3)
b2 = np.random.rand(3)

# layer1
a1 = np.matmul(X,W1) + b1
s1 = sigmoid(a1)

# layer2
a2 = np.matmul(s1,W2) + b2
h = sigmoid(a2)
h

array([[0.93532857, 0.77972063, 0.745988  ],
       [0.93756147, 0.78315943, 0.74911883],
       [0.93148085, 0.77086542, 0.73769332],
       [0.94333003, 0.79202863, 0.75740773],
       [0.93578061, 0.77758639, 0.74369121],
       [0.93744781, 0.78127135, 0.74717536],
       [0.93692792, 0.78178854, 0.74781731],
       [0.94069093, 0.78684175, 0.75237254],
       [0.93803481, 0.77954197, 0.74522634],
       [0.94059103, 0.78745247, 0.75304113]])

## 계층으로 클래스화 및 순전파 구현

In [10]:
# sigmoid layer의 순전파 구현
class Sigmoid:
    def __init__(self):
        self.params = []
        
    def forward(self,x):
        return 1 / (1 + np.exp(-x))

# H(x) = W*X + b     
class Affine: # 행렬의 내적을 아핀(Affine) 변환이라고 하며, Affine 계층을 통해 이 변환을 수행처리함 
    def __init__(self,W,b):
        self.params = [W,b]
        
    def forward(self,x) :
        W,b = self.params
        out = np.dot(x,W) + b
        return out

In [11]:
#  모델 구현
class TwoLayerNet:
    def __init__(self,input_size,hidden_size,output_size):
        I,H,O = input_size, hidden_size, output_size
        
        # Weight 과 bias 초기화
        W1 = np.random.rand(I,H)
        b1 = np.random.rand(H)
        
        W2 = np.random.rand(H,O)
        b2 = np.random.rand(O)
        
        # 계층 생성
        self.layers = [
            Affine(W1,b1),
            Sigmoid(),
            Affine(W2,b2),
            Sigmoid(),            
        ]
        
        self.params = []
        for layer in self.layers:
            self.params += layer.params
            
    def predict(self,x):
        for layer in self.layers:
            x = layer.forward(x)
        return x
    
# t = TwoLayerNet(2,4,3) 
# t.params

In [12]:
# 모든 가중치를 모은다
#         self.params = []
#         for layer in self.layers:
#             self.params += layer.params
a = ['W1','b1']
a += ['W2','b2']
a

['W1', 'b1', 'W2', 'b2']

In [13]:
X = np.random.rand(10,2)
model = TwoLayerNet(2,4,3) # shape을 정확히 맞추어 설정
# 여기에서는 학습 수행 부분은 없음
# random 값을 그대로 가중치(파라메터)로 사용
s = model.predict(X)
print(s,s.shape)

[[0.80204763 0.88051137 0.68057435]
 [0.78815855 0.86999717 0.67345346]
 [0.8022641  0.8805072  0.68016977]
 [0.77591681 0.86000028 0.66596115]
 [0.75658499 0.84529533 0.65706507]
 [0.79169286 0.87254719 0.67493575]
 [0.81355586 0.8891609  0.68603557]
 [0.76535135 0.85210388 0.66130164]
 [0.80590685 0.88308442 0.68125692]
 [0.78366732 0.86614821 0.67023629]] (10, 3)


In [14]:
model.params

[array([[0.24937251, 0.3680599 , 0.52133519, 0.93542998],
        [0.13263235, 0.96067397, 0.92139969, 0.86622496]]),
 array([0.85131445, 0.74543477, 0.24266289, 0.91771646]),
 array([[0.18156812, 0.54230984, 0.15001193],
        [0.38093331, 0.5061819 , 0.3755548 ],
        [0.61910424, 0.82575112, 0.17456437],
        [0.51775179, 0.25314427, 0.04833291]]),
 array([0.01263813, 0.31069537, 0.15086985])]