## Repeat Node

In [7]:
import numpy as np

# 순전파

D = 8
N = 7
x = np.random.rand(1,D)  # (1,8)
# x = np.random.rand(D,).reshape(1,-1)  # (1,8)
print(x, x.shape)
print('-'*70)

y = np.repeat(x,N,axis=0)  # 수직(행) 방향, axis=0
print(y, y.shape)

[[0.33827315 0.39762466 0.62439778 0.94366595 0.78599564 0.78234857
  0.6240581  0.71067929]] (1, 8)
----------------------------------------------------------------------
[[0.33827315 0.39762466 0.62439778 0.94366595 0.78599564 0.78234857
  0.6240581  0.71067929]
 [0.33827315 0.39762466 0.62439778 0.94366595 0.78599564 0.78234857
  0.6240581  0.71067929]
 [0.33827315 0.39762466 0.62439778 0.94366595 0.78599564 0.78234857
  0.6240581  0.71067929]
 [0.33827315 0.39762466 0.62439778 0.94366595 0.78599564 0.78234857
  0.6240581  0.71067929]
 [0.33827315 0.39762466 0.62439778 0.94366595 0.78599564 0.78234857
  0.6240581  0.71067929]
 [0.33827315 0.39762466 0.62439778 0.94366595 0.78599564 0.78234857
  0.6240581  0.71067929]
 [0.33827315 0.39762466 0.62439778 0.94366595 0.78599564 0.78234857
  0.6240581  0.71067929]] (7, 8)


In [11]:
# 역전파 : sum
dy = np.random.rand(N,D)
print(dy, dy.shape)  # (7, 8)
print('-'*70)
dx = np.sum(dy,axis=0,keepdims=True)  # 수직 방향 합, keepdims=True이면 2차원, Flase이면 1차원
print(dx, dx.shape)  # (1, 8)

[[0.0729196  0.06227804 0.0877057  0.0749236  0.21926435 0.9894172
  0.92923984 0.86431945]
 [0.00943409 0.92786936 0.84714286 0.13099146 0.62095059 0.85730336
  0.79013    0.59945452]
 [0.41990977 0.03833323 0.82462754 0.36102424 0.74108445 0.97786397
  0.1275924  0.57399758]
 [0.63767158 0.7691092  0.98940996 0.61777463 0.68729127 0.32145559
  0.76052393 0.44889394]
 [0.95970009 0.40227626 0.27860587 0.39592831 0.82657346 0.93107671
  0.79948917 0.10668866]
 [0.68990679 0.80185906 0.40246878 0.60572179 0.04218371 0.01030179
  0.35633794 0.71116097]
 [0.30160655 0.6893462  0.02932221 0.63319891 0.4449267  0.08442664
  0.41922718 0.83708208]] (7, 8)
----------------------------------------------------------------------
[[3.09114848 3.69107135 3.45928292 2.81956294 3.58227452 4.17184526
  4.18254047 4.14159719]] (1, 8)


## Sum Node

In [15]:
# 순전파

D,N = 8,7
x = np.random.rand(N,D)
print(x, x.shape)  # (7, 8)
print('-'*70)

y = np.sum(x,axis=0,keepdims=True)  # 수직 방향 합, keepdims=True이면 2차원, Flase이면 1차원
print(y, y.shape)  # (1, 8)

[[0.67243912 0.09711838 0.5240633  0.54970958 0.73015161 0.45373492
  0.54622644 0.19808965]
 [0.23131644 0.66480449 0.64466497 0.4268541  0.41595261 0.90694265
  0.80658622 0.45837701]
 [0.68289642 0.77287084 0.959434   0.90458874 0.59106809 0.68937787
  0.92458097 0.33080423]
 [0.94386712 0.10358962 0.83933465 0.4965158  0.65101754 0.13149328
  0.00586308 0.07049283]
 [0.47092303 0.14956824 0.22293084 0.26735238 0.68918458 0.30238256
  0.88531704 0.44920073]
 [0.61698889 0.67782474 0.18173931 0.77591969 0.27134685 0.58027324
  0.67052087 0.13506767]
 [0.76666546 0.76218478 0.62251602 0.47490037 0.78090166 0.54140128
  0.74299205 0.73722427]] (7, 8)
----------------------------------------------------------------------
[[4.38509647 3.2279611  3.9946831  3.89584066 4.12962294 3.60560579
  4.58208667 2.37925637]] (1, 8)


In [18]:
# 역전파

dy = np.random.rand(1,D)  # (1,8)
print(dy, dy.shape)
print('-'*70)

dx = np.repeat(dy,N,axis=0)  # 수직(행) 방향, axis=0
print(dx, dx.shape)

[[0.87020186 0.19942159 0.26475283 0.87328178 0.95324739 0.26596858
  0.40674157 0.00430925]] (1, 8)
----------------------------------------------------------------------
[[0.87020186 0.19942159 0.26475283 0.87328178 0.95324739 0.26596858
  0.40674157 0.00430925]
 [0.87020186 0.19942159 0.26475283 0.87328178 0.95324739 0.26596858
  0.40674157 0.00430925]
 [0.87020186 0.19942159 0.26475283 0.87328178 0.95324739 0.26596858
  0.40674157 0.00430925]
 [0.87020186 0.19942159 0.26475283 0.87328178 0.95324739 0.26596858
  0.40674157 0.00430925]
 [0.87020186 0.19942159 0.26475283 0.87328178 0.95324739 0.26596858
  0.40674157 0.00430925]
 [0.87020186 0.19942159 0.26475283 0.87328178 0.95324739 0.26596858
  0.40674157 0.00430925]
 [0.87020186 0.19942159 0.26475283 0.87328178 0.95324739 0.26596858
  0.40674157 0.00430925]] (7, 8)


## MatMul Node

In [19]:
class MatMul:
    def __init__(self,W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
        
    def forward(self,x):
        W = self.params
        out = np.dot(x,W)
        self.x = x
        return out
        
    def backward(self,dout):
        W = self.params
        dx = np.dot(dout,W.T)
        dw = np.dot(self.x.T,dout)
        self.grads[0][...] = dw  # 깊은 복사
        return dx

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(hex(id(a)),hex(id(b)))
a = b    # 얕은 복사
print(a)
print(hex(id(a)),hex(id(b)))
id(a) == id(b)

0x1257dcac670 0x1257dcb2d50
[4 5 6]
0x1257dcb2d50 0x1257dcb2d50


True

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a[...] = b  # 깊은 복사
print(a)
print(hex(id(a)),hex(id(b)))
id(a) == id(b)

[4 5 6]
0x1257dd12f80 0x1257dd12f30


False

In [22]:
# np.zeros_like
a = np.arange(12).reshape(3,4)
b = np.zeros_like(a)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Sigmoid 계층

In [24]:
class Sigmoid:
    def __init__(self):
        self.params, self.grads = [],[]
        self.out = None
        
    def forward(self,x):
        out = 1/(1+np.exp(-x))
        self.out = out
        return out
    
    def backward(self,dout):
        dx = dout*self.out*(1-self.out)
        return dx

## Affine 계층 : MatMul 노드에 bias를 더한 계층,  X*W + b

In [ ]:
class Affine:
    def __init__(self,W):
        self.params = [W,b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None
        
    def forward(self,x):
        W, b = self.params
        out = np.dot(x,W) + b
        self.x = x
        return out
        
    def backward(self,dout):
        W, b = self.params
        dx = np.dot(dout,W.T)
        dw = np.dot(self.x.T,dout)
        db = np.sum(dout,axis=0)
        
        self.grads[0][...] = dw  # deep copy
        self.grads[1][...] = db
        
        return dx

## Softmax with Loss 계층

In [28]:
class SoftmaxWithLoss:
    def __init__(self):
        self.params, self.grads = [],[]
        self.y = None  # softmax의 출력값
        self.t = None  # 정답 레이블
        
    def softmax(self,x):
        if x.ndim == 2:
            x = x-x.max(axis=1, keepdims=True)  # nan출력을 방지
            x = np.exp(x)
            x /= x.sum(axis=1, keepdims=True)
        elif x.dim == 1:
            x = x-np.max(x)
            x = np.exp(x)/np.sum(np.exp(x))
        return x
    
# https://smile2x.tistory.com/entry/softmax-crossentropy-%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC 
    def cross_entropy_error(self,y,t):  
        if y.ndim == 1:
            t = t.reshape(1, t.size)
            y = y.reshape(1, y.size)

        # 정답 데이터가 원핫 벡터일 경우 정답 레이블 인덱스로 변환
        if t.size == y.size:
            t = t.argmax(axis=1)

        batch_size = y.shape[0]

        return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size  # 1e-7은 log(0)으로 무한대가 나오는걸 방지

    def forward(self,x,t):
        self.t = t
        self.y = self.softmax(x)
        
        # 정답 데이터가 원핫 벡터일 경우 정답 레이블 인덱스로 변환
        if t.size == y.size:
            t = t.argmax(axis=1)
        
        loss = self.cross_entropy_error(self.y, self.t)
        return loss
    
    def backward(self,dout=1):
        batch_size = self.t.shape[0]
        
        # dx = (self.y-self.t)/batch_size  # 순수 Softmax 계층일 경우
        dx = self.y.copy()
        dx[np.arange(batch_size), self.t] -= 1
        dx *= dout
        dx = dx / batch_size

        return dx

In [26]:
# softmax 구현시에  지수값이 크면 overflow 발생으로 nan이 나오는 것을 방지하기 위해 입력 값의 최대값을 빼주어 사용한다
a = np.array([1010,1000,990])
print(np.exp(a))    # [inf inf inf]  , 무한대 값, 오버플로우 발생
x = np.exp(a)/np.sum(np.exp(a))
print(x)  # [nan nan nan]

c = np.max(a)
print(a - c)
x2 = np.exp(a - c)/np.sum(np.exp(a - c))
print(x2)  # [9.99954600e-01 4.53978686e-05 2.06106005e-09]

[inf inf inf]
[nan nan nan]
[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


C:\Users\Wonseok\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


### Weight 갱신

In [29]:
# 확률적 경사하강법(Stochastic Gradient Descent)
class SGD:
    def __init__(self,lr=0.01):
        self.lr = lr
        
    def update(self,params,grads):
        for i in range(len(params)):
            params[i] -= self.lr*grads[i]

In [30]:
class Adam:
    '''
    Adam (http://arxiv.org/abs/1412.6980v8)
    
    '''
    def __init__(self, lr=0.001, beta1=0.9, beta2=0.999):
        self.lr = lr
        self.beta1 = beta1
        self.beta2 = beta2
        self.iter = 0
        self.m = None
        self.v = None
        
    def update(self, params, grads):
        if self.m is None:
            self.m, self.v = [], []
            for param in params:
                self.m.append(np.zeros_like(param))
                self.v.append(np.zeros_like(param))
        
        self.iter += 1
        lr_t = self.lr * np.sqrt(1.0 - self.beta2**self.iter) / (1.0 - self.beta1**self.iter)

        for i in range(len(params)):
            self.m[i] += (1 - self.beta1) * (grads[i] - self.m[i])
            self.v[i] += (1 - self.beta2) * (grads[i]**2 - self.v[i])
            
            params[i] -= lr_t * self.m[i] / (np.sqrt(self.v[i]) + 1e-7)
            
# https://dalpo0814.tistory.com/29